backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "albums"
    label: "Photo Albums"
    folder: "content/albums"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Cover Image", name: "coverImage", widget: "image"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Photos", name: "photos", widget: "list", fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Caption", name: "caption", widget: "string"}
          - {label: "Alt Text", name: "alt", widget: "string"}}

  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "biography"
    label: "Biography"
    file: "content/biography.md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Profile Image", name: "profileImage", widget: "image"} 